---
- name: Install docker dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lsb-core
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Add dockers GPG key and repository to apt
  shell: '{{ item }}'
  args:
    executable: '/bin/bash'
  with_items:
    - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
    - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
    - 'apt-get update'
- name: Install docker
  package:
    name: "docker-ce"
    state: present
